import argparse
import csv
import math
import os
import random
import re
import sys
import importlib
from typing import Dict, List

import numpy as np
from PIL import Image
import torch
import torch.nn as nn
from sklearn.model_selection import KFold
from torch.utils.data import DataLoader, Dataset

CUR_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(CUR_DIR)
_local_src = os.path.join(CUR_DIR, "deeplabv3-plus-pytorch")
_legacy_src = os.path.join(PROJECT_ROOT, "deeplabv3-plus-pytorch")
if os.path.isdir(_local_src):
    DEEPLAB_SRC = _local_src
elif os.path.isdir(_legacy_src):
    DEEPLAB_SRC = _legacy_src
else:
    raise FileNotFoundError(
        f"deeplabv3-plus-pytorch not found. checked: {_local_src} and {_legacy_src}"
    )
if DEEPLAB_SRC not in sys.path:
    sys.path.insert(0, DEEPLAB_SRC)


def get_deeplab_class():
    mod = importlib.import_module("nets.deeplabv3_plus")
    return getattr(mod, "DeepLab")


def parse_args():
    parser = argparse.ArgumentParser(description="DeepLabv3+ KFold training on 2D slices with patient-level split.")
    parser.add_argument("--data_root", type=str, required=True, help="2D dataset root (generated by preprocess script).")
    parser.add_argument("--runs_root", type=str, default="./runs/Deeplabv3+")
    parser.add_argument("--num_classes", type=int, default=2)
    parser.add_argument("--backbone", type=str, default="mobilenet", choices=["mobilenet", "xception"])
    parser.add_argument("--downsample_factor", type=int, default=16, choices=[8, 16])
    parser.add_argument("--num_folds", type=int, default=5)
    parser.add_argument("--max_epochs", type=int, default=100)
    parser.add_argument("--early_stop_patience", type=int, default=20)
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--input_h", type=int, default=512)
    parser.add_argument("--input_w", type=int, default=512)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--only_fold", type=int, default=None)
    parser.add_argument("--pretrained_backbone", action="store_true")
    return parser.parse_args()


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def case_from_slice_name(name: str) -> str:
    stem = os.path.splitext(os.path.basename(name))[0]
    m = re.match(r"(.+)_slice\d+$", stem)
    return m.group(1) if m else stem


def load_train_samples(data_root: str) -> List[Dict[str, str]]:
    manifest = os.path.join(data_root, "train_manifest.csv")
    samples = []
    if os.path.exists(manifest):
        with open(manifest, "r", encoding="utf-8") as f:
            for r in csv.DictReader(f):
                samples.append(
                    {
                        "case_id": r["case_id"],
                        "image": os.path.join(data_root, r["image"]),
                        "label": os.path.join(data_root, r["label"]),
                    }
                )
    else:
        img_dir = os.path.join(data_root, "imagesTr")
        lbl_dir = os.path.join(data_root, "labelsTr")
        if not os.path.isdir(img_dir) or not os.path.isdir(lbl_dir):
            raise FileNotFoundError("imagesTr/labelsTr not found and train_manifest.csv missing.")
        for fn in sorted(os.listdir(img_dir)):
            if not fn.lower().endswith(".png"):
                continue
            lp = os.path.join(lbl_dir, fn)
            if not os.path.exists(lp):
                continue
            samples.append({"case_id": case_from_slice_name(fn), "image": os.path.join(img_dir, fn), "label": lp})

    if not samples:
        raise ValueError("No training samples found.")

    for s in samples:
        if not os.path.exists(s["image"]) or not os.path.exists(s["label"]):
            raise FileNotFoundError(f"Missing sample files: {s}")
    return samples


class Seg2DDataset(Dataset):
    def __init__(self, samples, input_h: int, input_w: int, augment: bool = False):
        self.samples = samples
        self.input_h = input_h
        self.input_w = input_w
        self.augment = augment

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        s = self.samples[idx]
        image = Image.open(s["image"]).convert("RGB")
        label = Image.open(s["label"])

        image = image.resize((self.input_w, self.input_h), Image.BILINEAR)
        label = label.resize((self.input_w, self.input_h), Image.NEAREST)

        if self.augment:
            if random.random() < 0.5:
                image = image.transpose(Image.FLIP_LEFT_RIGHT)
                label = label.transpose(Image.FLIP_LEFT_RIGHT)
            if random.random() < 0.5:
                image = image.transpose(Image.FLIP_TOP_BOTTOM)
                label = label.transpose(Image.FLIP_TOP_BOTTOM)
            if random.random() < 0.5:
                k = random.randint(1, 3)
                image = image.rotate(90 * k, resample=Image.BILINEAR)
                label = label.rotate(90 * k, resample=Image.NEAREST)

        image_np = np.asarray(image, dtype=np.float32) / 255.0
        image_np = (image_np - np.array([0.485, 0.456, 0.406], dtype=np.float32)) / np.array([0.229, 0.224, 0.225], dtype=np.float32)
        image_np = np.transpose(image_np, (2, 0, 1))
        label_np = np.asarray(label, dtype=np.int64)

        return torch.from_numpy(image_np), torch.from_numpy(label_np)


def dice_fg_score(logits: torch.Tensor, target: torch.Tensor, num_classes: int) -> float:
    pred = torch.argmax(logits, dim=1)
    valid = target >= 0
    pred = pred[valid]
    target = target[valid]
    if pred.numel() == 0:
        return 0.0

    dices = []
    for c in range(1, num_classes):
        p = pred == c
        t = target == c
        inter = (p & t).sum().item()
        denom = p.sum().item() + t.sum().item()
        if denom == 0:
            continue
        dices.append((2.0 * inter + 1e-6) / (denom + 1e-6))
    return float(np.mean(dices)) if dices else 0.0


def train_one_fold(args, fold: int, train_samples, val_samples, device: torch.device):
    fold_dir = os.path.join(args.runs_root, f"fold_{fold}")
    os.makedirs(fold_dir, exist_ok=True)

    best_ckpt = os.path.join(fold_dir, f"best_model_fold{fold}.pth")
    last_state = os.path.join(fold_dir, f"last_state_fold{fold}.pt")
    epoch_csv = os.path.join(fold_dir, "epoch_metrics.csv")

    train_ds = Seg2DDataset(train_samples, args.input_h, args.input_w, augment=True)
    val_ds = Seg2DDataset(val_samples, args.input_h, args.input_w, augment=False)

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, num_workers=args.workers, pin_memory=device.type == "cuda")
    val_loader = DataLoader(val_ds, batch_size=max(1, min(args.batch_size, 4)), shuffle=False, num_workers=args.workers, pin_memory=device.type == "cuda")

    DeepLab = get_deeplab_class()
    model = DeepLab(
        num_classes=args.num_classes,
        backbone=args.backbone,
        downsample_factor=args.downsample_factor,
        pretrained=args.pretrained_backbone,
    ).to(device)

    criterion = nn.CrossEntropyLoss(ignore_index=255)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max", factor=0.5, patience=max(3, args.early_stop_patience // 3), min_lr=1e-6)

    start_epoch = 0
    best_metric = -1.0
    best_epoch = -1
    epochs_no_improve = 0

    if args.resume and os.path.exists(last_state):
        state = torch.load(last_state, map_location=device)
        model.load_state_dict(state["model"])
        optimizer.load_state_dict(state["optimizer"])
        scheduler.load_state_dict(state["scheduler"])
        start_epoch = int(state["epoch"]) + 1
        best_metric = float(state["best_metric"])
        best_epoch = int(state["best_epoch"])
        epochs_no_improve = int(state["epochs_no_improve"])
        print(f"Resume fold {fold} from epoch {start_epoch + 1}")

    mode = "a" if (args.resume and os.path.exists(epoch_csv) and start_epoch > 0) else "w"
    with open(epoch_csv, mode, newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if mode == "w":
            writer.writerow(["epoch", "train_loss", "val_loss", "val_dice_fg", "lr", "is_best"])

        for epoch in range(start_epoch, args.max_epochs):
            model.train()
            train_loss = 0.0
            for imgs, labels in train_loader:
                imgs = imgs.to(device, non_blocking=True)
                labels = labels.to(device, non_blocking=True)
                optimizer.zero_grad(set_to_none=True)
                logits = model(imgs)
                loss = criterion(logits, labels)
                loss.backward()
                optimizer.step()
                train_loss += loss.item()

            train_loss /= max(1, len(train_loader))

            model.eval()
            val_loss = 0.0
            val_dices = []
            with torch.no_grad():
                for imgs, labels in val_loader:
                    imgs = imgs.to(device, non_blocking=True)
                    labels = labels.to(device, non_blocking=True)
                    logits = model(imgs)
                    loss = criterion(logits, labels)
                    val_loss += loss.item()
                    val_dices.append(dice_fg_score(logits, labels, args.num_classes))

            val_loss /= max(1, len(val_loader))
            val_dice = float(np.mean(val_dices)) if val_dices else 0.0
            if math.isnan(val_dice):
                val_dice = 0.0

            scheduler.step(val_dice)
            lr_now = optimizer.param_groups[0]["lr"]
            is_best = int(val_dice > best_metric)

            writer.writerow([epoch + 1, f"{train_loss:.6f}", f"{val_loss:.6f}", f"{val_dice:.6f}", f"{lr_now:.8f}", is_best])
            f.flush()

            print(f"Fold {fold} | Epoch {epoch + 1}/{args.max_epochs} | TrainLoss {train_loss:.4f} | ValLoss {val_loss:.4f} | ValDice(FG) {val_dice:.4f}")

            if is_best:
                best_metric = val_dice
                best_epoch = epoch + 1
                epochs_no_improve = 0
                torch.save(model.state_dict(), best_ckpt)
                print(f"Saved best model: {best_ckpt}")
            else:
                epochs_no_improve += 1

            torch.save(
                {
                    "epoch": epoch,
                    "model": model.state_dict(),
                    "optimizer": optimizer.state_dict(),
                    "scheduler": scheduler.state_dict(),
                    "best_metric": best_metric,
                    "best_epoch": best_epoch,
                    "epochs_no_improve": epochs_no_improve,
                },
                last_state,
            )

            if epochs_no_improve >= args.early_stop_patience:
                print(f"Early stopping fold {fold} at epoch {epoch + 1}")
                break

    return {
        "fold": fold,
        "best_epoch": best_epoch,
        "best_dice_fg": best_metric,
        "num_train": len(train_samples),
        "num_val": len(val_samples),
        "checkpoint": best_ckpt,
    }


def main():
    args = parse_args()
    set_seed(args.seed)
    os.makedirs(args.runs_root, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    samples = load_train_samples(args.data_root)

    case_ids = sorted({s["case_id"] for s in samples})
    if len(case_ids) < args.num_folds:
        raise ValueError(f"Not enough cases {len(case_ids)} for num_folds={args.num_folds}")

    print("=" * 88)
    print("DeepLabv3+ Training")
    print(f"Device: {device}")
    print(f"Cases: {len(case_ids)} | Slices: {len(samples)}")
    print(f"Folds: {args.num_folds}")
    print(f"Runs root: {args.runs_root}")
    print("=" * 88)

    kf = KFold(n_splits=args.num_folds, shuffle=True, random_state=args.seed)
    fold_results = []

    case_ids_np = np.array(case_ids)
    for fold, (tr_idx, va_idx) in enumerate(kf.split(case_ids_np)):
        if args.only_fold is not None and fold != args.only_fold:
            continue

        tr_cases = set(case_ids_np[tr_idx].tolist())
        va_cases = set(case_ids_np[va_idx].tolist())

        tr_samples = [s for s in samples if s["case_id"] in tr_cases]
        va_samples = [s for s in samples if s["case_id"] in va_cases]

        print(f"\n===== Fold {fold} =====")
        print(f"Train cases/slices: {len(tr_cases)}/{len(tr_samples)} | Val cases/slices: {len(va_cases)}/{len(va_samples)}")

        result = train_one_fold(args, fold, tr_samples, va_samples, device)
        fold_results.append(result)

    if not fold_results:
        raise ValueError("No fold was trained. Check --only_fold")

    cv_csv = os.path.join(args.runs_root, "cv_results.csv")
    with open(cv_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["fold", "best_epoch", "best_dice_fg", "num_train", "num_val", "checkpoint"])
        for r in fold_results:
            w.writerow([r["fold"], r["best_epoch"], f"{r['best_dice_fg']:.6f}", r["num_train"], r["num_val"], r["checkpoint"]])

    scores = np.array([r["best_dice_fg"] for r in fold_results], dtype=np.float32)
    print("\n===== CV Summary =====")
    print(f"Saved: {cv_csv}")
    print(f"Dice(FG) mean={scores.mean():.4f}, std={scores.std(ddof=0):.4f}")


if __name__ == "__main__":
    main()
